sudo: false
language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
branches:
  except:
    - /.*wip.*/i
script: "mvn -T4 clean package"
after_success:
after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn clean deploy jacoco:report coveralls:report --settings ~/settings.xml
